import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './my-component/Navbar'
import SideBar from './my-component/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark' >
      <body className={inter.className} >
        <Navbar/>

        <div className='flex'>
          <div className='w-1/5'><SideBar /></div>
          <div className='w-full'>{children}</div>
        </div>
        </body>
    </html>
  )
}
